export interface BundleTier {
  minP: number;
  pct: number;
  display: string;
}

export const CARPET_MIN_BOOKING_P: number;
export const CARPET_ITEM_PRICES_P: Readonly<Record<string, number>>;
export const STAIRS_FIRST_P: number;
export const STAIRS_EXTRA_P: number;
export const CARPET_BUNDLE_TIERS: readonly BundleTier[];
export const EOT_BASE_PRICES_P: Readonly<Record<string, number>>;
export const EOT_TAILORED_QUOTE_SIZE: 'bed5';
export const EOT_HOUSE_ADJUSTMENT_P: number;
export const EOT_EXTRA_BATH_P: number;
export const EOT_EXTRA_WC_P: number;
export const EOT_EXTRA_AREAS_P: Readonly<Record<string, number>>;
export const EOT_SCOPE_CREDITS_P: Readonly<Record<string, number>>;
export const EOT_SCOPE_CREDIT_MAX_P: number;
export const EOT_SCOPE_CREDIT_MAX_PERCENT: number;
export const EOT_CARPET_ADDON_PRICES_P: Readonly<Record<string, number>>;
export const MOVEIN_BASE_PRICES_P: Readonly<Record<string, number>>;
export const MOVEIN_EXTRA_BATH_P: number;
export const AFTER_BUILDERS_FROM_PRICES_P: Readonly<Record<string, number>>;
export const AFTER_BUILDERS_START_FROM_P: number;
export const COMMERCIAL_REGULAR_HOURLY_P: number;
export const COMMERCIAL_REGULAR_MIN_HOURS: number;
export const COMMERCIAL_REGULAR_MIN_CHARGE_P: number;
export const COMMERCIAL_ONCEOFF_HOURLY_P: number;
export const COMMERCIAL_ONCEOFF_MIN_HOURS: number;
export const COMMERCIAL_ONCEOFF_MIN_CHARGE_P: number;
export const COMMERCIAL_SHOP_CAFE_FROM_P: number;
export const COMMERCIAL_COMMUNAL_FROM_P: number;
export const COMMERCIAL_CARPET_PER_SQM_P: number;
export const COMMERCIAL_CARPET_MIN_P: number;
export const COMMERCIAL_EOL_FROM_P: number;
export const COMMERCIAL_AFTER_BUILDERS_FROM_P: number;
export const ADDON_PRICES_P: Readonly<Record<string, number>>;
export const EOT_CARPET_BUNDLE_P: Readonly<Record<string, number>>;
export const DEPOSIT_P: number;
export const PARKING_ESTIMATE_P: number;
export const CONGESTION_CHARGE_P: number;
export const LEGACY_CARPET_BASE_PRICES_P: Readonly<Record<string, number>>;
export const LEGACY_DEEP_ADDON_PRICES_P: Readonly<Record<string, number>>;
export const WINDOW_PRICES_P: Readonly<Record<string, number>>;
export const GUTTER_PRICES_P: Readonly<Record<string, number>>;
export const GENERAL_MIN_BOOKING_P: number;
